--- 
- hosts: webservers 
  become: yes 
  vars_files: 
    - keys.yml 
  tasks: 
    - name: Gather_Snapshot_Facts
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
	      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
	      ec2_region: "{{ AWS_REGION }}"
        state: list
        resource: i-008f253562341a32
      register: tags
    - name: Display tags
      debug:
        var: tags.tags
    - name: ad tags to resource
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
	      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
	      ec2_region: "{{ AWS_REGION }}"
        resource: snap-788453df952335623c0d
        tags:
          system: erp
          version: 1.2
        state: present
        
