--- 
- hosts: webservers 
  become: yes 
  vars_files: 
    - keys.yml 
  tasks: 
    - name: Create new ABS Volume
      ec2_vol:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
		aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
		ec2_region: "{{ AWS_REGION }}"
        zone: us-east-id
        volume size: "1"
        name: web_volume
        device_name: /dev/xvf
      register: vol_info
    - debug:
        var: vol_info
