---
- hosts
  gather_facts: no
  vars_filter:
    - keys.yml
  tasks:
    - name: Get AMI Facts 
	ec2_ami_facts:
	  aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
	  aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
	  ec2_region: "{{ AWS_REGION }}"
	  filters:
	    description: "*redhat*"
	  register: ami_facts
	- name: Output Information
	  debug:
	    msg: "{{ item.description}}"
	  loop_control:
	    label: "{{ item_image_id }}"
	  loop: "{{ ami_facts.images }}"
