- hosts: webservers
   gather_facts: no
   vars_files:
     - /home/ansible/env_vars.yml
   remote_user: ec2-user
   tasks:
     - name: Wait for SSH to come up
       wait_for_connection:
         delay: 5
         timeout: 90

     - name: Collect instance facts
       ec2_metadata_facts:

     - name: Install HTTPD
       become: yes
       yum:
         name: httpd
         state: present

     - name: Start HTTPD
       become: yes
       service:
         name: httpd
         state: started
         enabled: yes

     - name: Deploy content
       become: yes
       template:
         src: /home/ansible/index.html.j2
         dest: /var/www/html/index.html
